"""CLI: Batch Judge (Pooling) for narratives.

python scripts/batch_judge.py --prepare --drafts out_batch/drafts.jsonl
python scripts/batch_judge.py --submit
python scripts/batch_judge.py --download --job-name batchJobs/456
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
import os
import dotenv

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.sentences import normalize_for_identity
from src.generate import GenerationConfig

try:
    from google import genai
except ImportError:
    pass

def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--prepare", action="store_true", help="Prepare the batch requests file")
    p.add_argument("--submit", action="store_true", help="Upload file and submit batch job")
    p.add_argument("--download", action="store_true", help="Download and process a completed batch job")
    
    p.add_argument("--drafts", help="path to drafts.jsonl (required for --prepare)")
    p.add_argument("--out", default="out_batch", help="output directory")
    p.add_argument("--model", default="gemini-3.7-flash")
    p.add_argument("--job-name", help="Job name (e.g. batchJobs/456) required for --download")
    return p.parse_args(argv)

def get_client() -> 'genai.Client':
    dotenv.load_dotenv(Path(__file__).resolve().parent.parent.parent / ".env")
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        for k, v in os.environ.items():
            if k.startswith("GEMINI_API_KEY") and v.strip():
                api_key = v.strip().strip('"').strip("'")
                break
    if not api_key:
        raise ValueError("No GEMINI_API_KEY found.")
    return genai.Client(api_key=api_key)

def do_prepare(args: argparse.Namespace, out_dir: Path) -> None:
    if not args.drafts:
        print("ERROR: --drafts required for --prepare")
        sys.exit(1)
        
    out_dir.mkdir(parents=True, exist_ok=True)
    req_file = out_dir / "judge_requests.jsonl"
    reps_file = out_dir / "judge_reps.jsonl" # To keep track of mapping
    
    count = 0
    with open(args.drafts, encoding="utf-8") as fin, \
         open(req_file, "w", encoding="utf-8") as freq, \
         open(reps_file, "w", encoding="utf-8") as freps:
         
        for line in fin:
            data = json.loads(line)
            signal_id = data["signal_id"]
            per_sample = data["per_sample"]
            
            # 1. Exact-duplicate collapse via normalize_for_identity
            order = []
            exact = {}
            for sample_index, sentences in enumerate(per_sample):
                for sentence in sentences:
                    key = normalize_for_identity(sentence)
                    if not key: continue
                    if key not in exact:
                        exact[key] = {"text": sentence, "appears_in": [], "variants": [sentence]}
                        order.append(key)
                    if sample_index not in exact[key]["appears_in"]:
                        exact[key]["appears_in"].append(sample_index)
            
            reps = [exact[k]["text"] for k in order]
            freps.write(json.dumps({"signal_id": signal_id, "order": order, "exact": exact, "reps": reps}) + "\n")
            
            prompt = (
                "Here is a list of sentences generated by an AI. Group them into clusters based on whether they assert the same core facts.\n"
                "Ignore minor editorial differences (e.g., 'this is notable', 'this is the primary evidence', or mentions of triggering a specific rule) "
                "as long as the underlying hard data and actions described (e.g., '4 visits to leak-publication sites') are the same.\n"
                "Return the 0-based indices of the sentences in each cluster.\n\n"
            )
            for i, text in enumerate(reps):
                prompt += f"[{i}] {text}\n"

            req = {
                "request_id": signal_id,
                "request": {
                    "model": f"models/{args.model}",
                    "contents": [{"role": "user", "parts": [{"text": prompt}]}],
                    "generationConfig": {
                        "temperature": 0.0,
                        "responseMimeType": "application/json",
                        "responseSchema": {
                            "type": "OBJECT",
                            "properties": {
                                "clusters": {
                                    "type": "ARRAY",
                                    "items": {
                                        "type": "OBJECT",
                                        "properties": {
                                            "sentence_indices": {
                                                "type": "ARRAY",
                                                "items": {"type": "INTEGER"}
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            freq.write(json.dumps(req) + "\n")
            count += 1
            
    print(f"Prepared {count} judge requests in {req_file}")

def do_submit(args: argparse.Namespace, out_dir: Path) -> None:
    req_file = out_dir / "judge_requests.jsonl"
    if not req_file.exists():
        print(f"ERROR: {req_file} not found. Run --prepare first.")
        sys.exit(1)
        
    client = get_client()
    print(f"Uploading {req_file} to Gemini File API...")
    file_obj = client.files.upload(
        file=str(req_file),
        config={"mime_type": "application/jsonl"}
    )
    print(f"Uploaded as: {file_obj.name}")
    
    print("Creating batch job for judge...")
    job = client.batches.create(
        model=args.model,
        src=file_obj.name
    )
    print(f"Batch job created successfully!")
    print(f"JOB NAME: {job.name}")
    print(f"State: {job.state}")
    
    state_file = out_dir / "judge_job.txt"
    state_file.write_text(job.name)
    print(f"Saved job name to {state_file}")

def do_download(args: argparse.Namespace, out_dir: Path) -> None:
    job_name = args.job_name
    if not job_name:
        state_file = out_dir / "judge_job.txt"
        if state_file.exists():
            job_name = state_file.read_text().strip()
        else:
            print("ERROR: --job-name required or judge_job.txt must exist.")
            sys.exit(1)
            
    client = get_client()
    print(f"Checking status for {job_name}...")
    job = client.batches.get(name=job_name)
    print(f"Current State: {job.state}")
    
    if job.state != "SUCCEEDED":
        print("Job has not succeeded yet. Please try again later.")
        sys.exit(1)
        
    file_name = None
    if job.dest and job.dest.file_name:
        file_name = job.dest.file_name
        
    if not file_name:
        print("ERROR: No output file name found in batch job.")
        sys.exit(1)
        
    print(f"Downloading results from file: {file_name}...")
    output_data = client.files.download(file=file_name)
    
    out_file = out_dir / "judge_raw_responses.jsonl"
    out_file.write_bytes(output_data)
    print(f"Saved raw responses to {out_file}")
    
    # Load original drafts and rep mapping
    drafts_by_id = {}
    with open(out_dir / "drafts.jsonl", encoding="utf-8") as f:
        for line in f:
            d = json.loads(line)
            drafts_by_id[d["signal_id"]] = d
            
    reps_by_id = {}
    with open(out_dir / "judge_reps.jsonl", encoding="utf-8") as f:
        for line in f:
            r = json.loads(line)
            reps_by_id[r["signal_id"]] = r
            
    final_file = out_dir / "narratives.jsonl"
    count = 0
    with open(out_file, "r", encoding="utf-8") as fin, open(final_file, "w", encoding="utf-8") as fout:
        for line in fin:
            if not line.strip(): continue
            resp = json.loads(line)
            signal_id = resp.get("request_id")
            
            try:
                content = resp["response"]["candidates"][0]["content"]["parts"][0]["text"]
                data = json.loads(content)
                clusters_data = data.get("clusters", [])
                index_groups = [c.get("sentence_indices", []) for c in clusters_data]
            except Exception as e:
                print(f"Failed to parse judge output for {signal_id}: {e}")
                continue
                
            draft_data = drafts_by_id[signal_id]
            rep_data = reps_by_id[signal_id]
            order = rep_data["order"]
            exact = rep_data["exact"]
            
            # Map index groups to clusters
            clusters = []
            assignment = {}
            for indices in index_groups:
                keys = [order[i] for i in indices if i < len(order)]
                if keys:
                    clusters.append({"keys": keys})
                    for k in keys:
                        assignment[k] = len(clusters) - 1
            
            # Ensure any sentences not clustered by the LLM get their own cluster
            for key in order:
                if key not in assignment:
                    clusters.append({"keys": [key]})
                    assignment[key] = len(clusters) - 1
                    
            # Build the sentences[] array
            sentences_out = []
            for i, cluster in enumerate(clusters, start=1):
                members = [exact[k] for k in cluster["keys"]]
                appears = []
                variants = []
                for m in members:
                    for s in m["appears_in"]:
                        if s not in appears: appears.append(s)
                    for v in m["variants"]:
                        if v not in variants: variants.append(v)
                sentences_out.append({
                    "sentence_id": f"s{i:03d}",
                    "text": members[0]["text"],
                    "variants": variants,
                    "n_variants": len(variants),
                    "appears_in": sorted(appears),
                    "n_samples": len(appears),
                })
                
            # Build the sentence_ids per sample
            ids_per_sample = []
            for sample_index, sentences in enumerate(draft_data["per_sample"]):
                seen = []
                for sentence in sentences:
                    key = normalize_for_identity(sentence)
                    if not key or key not in assignment: continue
                    sid = f"s{assignment[key] + 1:03d}"
                    if sid not in seen:
                        seen.append(sid)
                ids_per_sample.append(seen)
                
            cfg = GenerationConfig(model="gemini-3.7-flash", pooling_method="semantic", pooling_threshold=0.85, embed_model="gemini-3.7-flash")
            
            final_record = {
                "signal_id": signal_id,
                "model": cfg.model,
                "prompt_version": cfg.prompt_version,
                "temperature": cfg.temperature,
                "pooling": cfg.pooling_metadata(),
                "temperature_supported": True, # Batch API supports it
                "k": len(draft_data["drafts"]),
                "seed": None,
                "evidence_fact_ids": [], # we'd need original signal for this, skip for batch processing simplicity unless passed
                "narratives": [
                    {"sample_index": i, "text": draft_data["drafts"][i], "sentence_ids": ids_per_sample[i]}
                    for i in range(len(draft_data["drafts"]))
                ],
                "sentences": sentences_out
            }
            fout.write(json.dumps(final_record) + "\n")
            count += 1
            
    print(f"Successfully processed {count} signals to {final_file}")

def main(argv: list[str] | None = None) -> None:
    args = _parse_args(argv)
    out_dir = Path(args.out)
    
    if args.prepare:
        do_prepare(args, out_dir)
    elif args.submit:
        do_submit(args, out_dir)
    elif args.download:
        do_download(args, out_dir)
    else:
        print("Please specify one of: --prepare, --submit, --download")

if __name__ == "__main__":
    main()
